### ISSUE TITLE
Unable to flash china miui rom

### ISSUE THREAD

**Issue by Rakau** [nebrassy/device_xiaomi_renoir-TWRP#1]

**Comment by Rakau** [comment]
![Screenshot_2021-08-10-02-16-26](https://user-images.githubusercontent.com/33389179/128828510-96839a07-e697-4f27-ac54-dfe1269dee4e.png)

**Comment by nebrassy** [comment]
Flashing stock only works on miui recovery

**Comment by Rakau** [comment]
> Flashing stock only works on miui recovery

OK，Thanks
