### ISSUE TITLE
Merge Android-12.1 branch into official repo and make a build

### ISSUE THREAD

**Issue by reenberg** [nebrassy/device_xiaomi_renoir-TWRP#2]
@nebrassy, could you please merge the Android-12.1 branch into the official repo and make a 3.7.0 release with Android 12 support?

The current release with Android 11 support can't decrypt the /data partition of my MIUI 12.6 rom, so it is quite a hassle trying to update to MIUI 14, when it is not possible to access the partition where the rom was downloaded to.

Thanks in advance.

**Comment by reenberg** [comment]
For reference, I stumpled upon a custom 3.7.0_12 build that works and can decrypt the /data partition, but an official build would be more trustworthy.
https://xdaforums.com/t/recovery-11-official-teamwin-recovery-project.4306807/page-11#post-88871505

**Comment by nebrassy** [comment]
unfortunately it's not that simple, and I don't have any header v3 devices anymore so can't work on any of them, if anyone else wants to maintain renoir officially they can apply
